# -*- coding: utf-8 -*-
"""_main_.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nOGaRYByNWpYiXXGpHw1TX9xD6UIr6T2

###install Ba
"""

!jupyter nbconvert --ClearOutputPreprocessor.enabled=True \
--inplace your_notebook.ipynb

from IPython.display import clear_output

clear_output(wait=True)

!pip install -qU langchain langchain-community langchain-text-splitters langchain-groq langchain-huggingface faiss-cpu sentence-transformers groq pydantic pypdf gradio

"""### IMPORTS LIB"""

import os
import uuid
import time
from datetime import datetime
import random
import logging
from pathlib import Path
import re
import json

import torch
import gradio as gr

from google.colab import files, userdata
from groq import Groq
from langchain_groq import ChatGroq

from transformers import AutoTokenizer
from langchain_text_splitters import RecursiveCharacterTextSplitter
from langchain_huggingface import HuggingFaceEmbeddings
from langchain_community.document_loaders import PyPDFLoader
from langchain_community.vectorstores import FAISS ,DistanceStrategy

from langchain_community.chat_message_histories import ChatMessageHistory

"""### LOAD GROQ API KEY SECURELY

"""

GROQ_API_KEY = userdata.get("groq")

if not GROQ_API_KEY:
    raise ValueError("GROQ API KEY not found in Colab Secrets")

os.environ["GROQ_API_KEY"] = GROQ_API_KEY
print(" GROQ API KEY Loaded Successfully Tmaam")

"""###uploade files"""

uploaded = files.upload()
text = list(uploaded.keys())[0]
print("Uploaded:", text)

loader = PyPDFLoader(text)
documents = loader.load()

"""###Show All Pages"""

for i, doc in enumerate(documents):

    print(".." * 50)
    print(f"PAGE: {i+1}")
    print(f"SOURCE: {doc.metadata}")
    print(".." * 50)
    print(doc.page_content[:1500])
    print("\n")

"""###Tokenization , Chunking"""

tokenizer = AutoTokenizer.from_pretrained(
    "intfloat/multilingual-e5-base")

def clean_text(text):
    text = re.sub(r'\s+',' ', text)
    return text.strip()

def token_len(text):
    return len(tokenizer.encode(text))

random.seed(101)
random.shuffle(documents)

splitter = RecursiveCharacterTextSplitter(
    chunk_size=800,
    chunk_overlap=200,
    length_function=token_len,
    separators=["\n# ","\n## ","\n### ","\n\n","\n",". ","؟ ","! ","، "," ",""])

chunks = splitter.split_documents(documents)

print(f"Number of chunks: {len(chunks)}")
print(chunks[0].page_content) #1

"""###Embeddings"""

device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Using device is: {device}")
embedding_model = HuggingFaceEmbeddings(
    model_name="intfloat/multilingual-e5-base",
    model_kwargs={"device": device},
    encode_kwargs={"normalize_embeddings": True} )

"""###Vectorstore

"""

for i, doc in enumerate(chunks):
    doc.metadata["chunk_id"] = i

if os.path.exists("faiss_index"):
    vectorstore = FAISS.load_local(
        "faiss_index",
        embedding_model,
        allow_dangerous_deserialization=True)
else:
    vectorstore = FAISS.from_documents(
              documents=chunks,
              embedding=embedding_model,
   distance_strategy=DistanceStrategy.COSINE)

vectorstore.save_local("faiss_index")

"""###retriever"""

retriever = vectorstore.as_retriever(
    search_type="mmr",
    search_kwargs={
        "k": 4,
        "fetch_k": 10,
        "lambda_mult": 0.5})

"""###Groq client"""

client = Groq(
    api_key=os.environ["GROQ_API_KEY"])

"""###Chat_Message_History"""

memory_store = {}
WINDOW_SIZE = 8

def get_history(session_id: str):
    if session_id not in memory_store:
        memory_store[session_id] = ChatMessageHistory()
    return memory_store[session_id]

def get_recent_messages(session_id: str):
    history = get_history(session_id)
    messages = history.messages[-WINDOW_SIZE * 2:]
    formatted_messages = []

    for msg in messages:
        if msg.type == "human":
            formatted_messages.append({
                "role": "user",
                "content": msg.content
            })
        elif msg.type == "ai":
            formatted_messages.append({
                "role": "assistant",
                "content": msg.content
            })

    return formatted_messages

def ask(question: str, session_id: str = "default"):
    try:
        question = question.strip()

        if not question:
            return "Please enter a question."

        search_query = f"query: {question}"

        docs = retriever.invoke(search_query)

        if not docs:
            return "I don't have information about this question"

        context_parts = []

        for i, doc in enumerate(docs, start=1):
            chunk = doc.page_content.replace("passage:", "").strip()
            source = doc.metadata.get("source", "")

            if source:
                context_parts.append(
                    f"[Document {i}]\nSource: {source}\n{chunk}"
                )
            else:
                context_parts.append(
                    f"[Document {i}]\n{chunk}"
                )

        context = "\n\n".join(context_parts)

        history = get_history(session_id)

        messages = [{
            "role": "system",
            "content": """

You are a professional AI assistant representing Croco IT.

Your role:
You are the official Croco IT assistant. You help users understand the company’s services, products, and technologies in a clear, accurate, and professional way.

Core Rules:
1. Use ONLY the information provided in the Knowledge Base Context.
2. Never guess, infer, or invent any information.
3. If the answer is not explicitly found in the context, respond exactly:
   "I don't have information about this question"
4. Never mention or refer to:
   - Context
   - Documents
   - Chunks
   - Knowledge Base
   - Internal processing or system behavior

Language Rule:
- Always respond in the SAME language used by the user.

Answer Style:
- Start with a clear direct answer.
- Then provide supporting details if needed.
- Keep responses concise, structured, and professional.
- Use Markdown formatting when helpful.
- Use bullet points for lists.

Services / Products Explanations:
When relevant, include:
- Description
- Benefits
- Technologies (ONLY if explicitly present in context)

Conversation Behavior:
- If the user sends greetings (e.g. "hello", "hi", "السلام عليكم"):
  Respond politely in a professional tone.
- If the message is casual and unrelated to Croco IT:
  Respond politely, then gently guide the conversation toward Croco IT services.
- If the question is unclear:
  Ask a short clarification question.

Strict Restrictions:
- Do NOT repeat phrases unnecessarily.
- Do NOT provide unverified information.
- Do NOT create fake links, services, or claims.
- Do NOT express personal opinions.

Scope Control:
- If the question is outside Croco IT scope, respond exactly:
  "This question is outside the scope of the information available about Croco IT"

Memory Usage:
- You may use conversation history ONLY to maintain context of the conversation flow.
- Never use it as a factual source.

Goal:
Provide accurate, professional, and human-like support responses strictly based on the provided knowledge base.


"""}]

        # ADD CHAT HISTORY
        history_messages = get_recent_messages(session_id)

        if history_messages:
            messages.extend(history_messages)

        # CURRENT QUESTION
        messages.append({
            "role": "user",
            "content": f"""
Knowledge Base Context:{context}
Current User Question:{question}
Remember:
Answer only from the Knowledge Base Context.
If information is missing, respond exactly:
I don't have information about this question
"""})

        # LLM
        response = client.chat.completions.create(
            model="llama-3.3-70b-versatile",
            temperature=0.1,
            max_tokens=601,
            messages=messages)

        answer = response.choices[0].message.content.strip()

        # SAVE MEMORY
        if answer:
            history.add_user_message(question)
            history.add_ai_message(answer)

        return answer

    except Exception as e:
        return f"Error: {str(e)}"

"""###GUI"""

# AUTH (Colab Secrets + Local fallback)
try:
    VALID_USERNAME = userdata.get("VALID_USERNAME")
    VALID_PASSWORD = userdata.get("VALID_PASSWORD")

    if not VALID_USERNAME:
        VALID_USERNAME = os.getenv("VALID_USERNAME")

    if not VALID_PASSWORD:
        VALID_PASSWORD = os.getenv("VALID_PASSWORD")

except Exception:
    VALID_USERNAME = os.getenv("VALID_USERNAME")
    VALID_PASSWORD = os.getenv("VALID_PASSWORD")


# MEMORY SYSTEM
memory_store = {}
WINDOW_SIZE = 8


def get_history(session_id: str):
    if session_id not in memory_store:
        memory_store[session_id] = ChatMessageHistory()
    return memory_store[session_id]


def get_recent_messages(session_id: str):
    history = get_history(session_id)
    messages = history.messages[-WINDOW_SIZE * 2:]

    out = []
    for msg in messages:
        role = "user" if msg.type == "human" else "assistant"
        out.append({"role": role, "content": msg.content})

    return out

def clear_chat(session_id):
    if session_id in memory_store:
        memory_store[session_id] = ChatMessageHistory()
    return [], session_id


# LOGIN
def login(u, p):
    if u == VALID_USERNAME and p == VALID_PASSWORD:
        sid = str(uuid.uuid4())

        return (
            gr.update(visible=False),   # login panel
            gr.update(visible=True),    # chat panel
            sid,
            [],
            f"Session: {sid[:8]}"
        )

    return (
        gr.update(visible=True),
        gr.update(visible=False),
        "",[]," Invalid Username Or Password"
    )


# CHAT WRAPPER → RAG
def chat_fn(message, history, session_id):
    if not session_id:
        return history, ""

    answer = ask(message, session_id)

    history.append({"role": "user", "content": message})
    history.append({"role": "assistant", "content": answer})

    return history, ""

# UI
with gr.Blocks(theme=gr.themes.Soft(), title="Croco IT RAG System") as demo:

    session_state = gr.State("")

    login_panel = gr.Column(visible=True)
    chat_panel = gr.Column(visible=False)

    with login_panel:
        gr.Markdown(" Croco IT Login System")

        username = gr.Textbox(label="Username")
        password = gr.Textbox(label="Password", type="password")

        login_btn = gr.Button("Login", variant="primary")
        login_status = gr.Textbox(label="Status", interactive=False)

    with chat_panel:
        gr.Markdown("Croco IT AI Assistant")

        session_box = gr.Textbox(label="Session ID", interactive=False)

        chatbot = gr.Chatbot(height=450)

        with gr.Row():
            msg = gr.Textbox(label="Message", scale=8)
            send = gr.Button("Send", variant="primary", scale=2)

        clear = gr.Button("Clear Chat")

    # login
    login_btn.click(
        login,
        [username, password],
        [login_panel, chat_panel, session_state, chatbot, login_status]
    ).then(
        lambda sid: sid,
        session_state,
        session_box)
    # send
    send.click(
        chat_fn,
        [msg, chatbot, session_state],
        [chatbot, msg])

    msg.submit(
        chat_fn,
        [msg, chatbot, session_state],
        [chatbot, msg])

    # clear
    clear.click(
        clear_chat,
        [session_state],
        [chatbot, session_state])

demo.launch()













































































